# Generated by Django 6.0.1 on 2026-02-19 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autobuses', to='zonas.zona')),
            ],
        ),
    ]
